front/routes/web.php
<?php

use App\Http\Controllers\PremisesController;
use App\Http\Controllers\ServicesController;
use App\Http\Controllers\StartController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', static function () {
    return view('home');
});

Route::get('/', [StartController::class, 'start'])->name('home');
Route::get('/gallery', [StartController::class, 'gallery'])->name('gallery');
Route::get('/rules', [StartController::class, 'rules'])->name('rules');
Route::get('/booking', [StartController::class, 'booking'])->name('booking');
Route::get('/contacts', [StartController::class, 'contacts'])->name('contacts');

Route::group(['prefix' => '', 'as' => 'premises.'], function ($router) {
    Route::get('/houses', [PremisesController::class, 'houses'])->name('houses');
    Route::get('/gazebos', [PremisesController::class, 'gazebos'])->name('gazebos');
});

Route::group(['prefix' => 'services', 'as' => 'services.'], function ($router) {
    $router->get('/', [ServicesController::class, 'services'])->name('index');
    $router->get('/fishing', [ServicesController::class, 'fishing'])->name('fishing');
    $router->get('/pool', [ServicesController::class, 'pool'])->name('pool');
    $router->get('/family-holiday', [ServicesController::class, 'family'])->name('family');
    $router->get('/birthday', [ServicesController::class, 'birthday'])->name('birthday');
    $router->get('/corporate', [ServicesController::class, 'corporate'])->name('corporate');
});

front/resources/views/partials/breadcrumbs.blade.php
<ol class="breadcrumbs" itemscope="" itemtype="https://schema.org/BreadcrumbList">
    <li class="breadcrumbs__item" itemprop="itemListElement" itemscope="" itemtype="https://schema.org/ListItem">
        <a class="breadcrumbs__link" itemprop="item" href="{{ route('home') }}" title="Главная">
            <span itemprop="name">Главная</span>
            <meta itemprop="position" content="0"/>
        </a>
    </li>
    <li class="breadcrumbs__item" itemprop="itemListElement" itemscope="" itemtype="https://schema.org/ListItem">
        <a class="breadcrumbs__link" itemprop="item" href="{{ route('services.index') }}" title="Услуги">
            <span itemprop="name">Услуги</span>
            <meta itemprop="position" content="1"/>
        </a>
    </li>
    <li class="breadcrumbs__item" itemprop="itemListElement" itemscope="" itemtype="https://schema.org/ListItem">
        <span>{{ $title }}</span>
    </li>
</ol>

front/resources/views/partials/callback.blade.php
<!-- Обратный звонок-->
<div class="modal modal--center" id="callback-modal">
    <div class="modal__overlay" data-modal-close=""></div>
    <div class="modal__inner modal__inner--center modal__inner--medium">
        <div class="modal__head">
            <div class="modal__title">Заказать обратный звонок</div>
            <button class="modal__close modal__close--center" aria-label="Закрыть модальное окно" data-modal-close=""></button>
        </div>
        <div class="modal__content">
            <div class="modal__text">Оставьте свой номер телефона и наш менеджер свяжется с вами в ближайшее время</div>
            <form class="form form--feedback ajax-form" action="{{ route('callbackSend') }}" id="callback-form" method="post">
                @csrf
                <div class="field">
                    <input class="field__input field__input--default  field__input--gray" id="callback-name" type="text" name="name" required="required"/>
                    <label class="field__label field__label--gray" for="callback-name">Ваше имя</label>
                </div>
                <div class="field">
                    <input class="field__input field__input--default  field__input--gray" id="callback-phone" type="tel" name="phone" required="required"/>
                    <label class="field__label field__label--gray" for="callback-phone">Телефон</label>
                </div>
                <button class="button button--large button--yellow button--full button--text-gray" type="submit"><span class="button__text">Жду звонка</span>
                </button>
            </form>
            <div class="form-message form-message--gray">
                Нажимая на кнопку вы даете согласие на обработку персональных данных и соглашаетесь с 
                <a href="#" title="Соглашение на обработку персональных данных">Политикой конфиденциальности</a>
            </div>
        </div>
    </div>
</div>
<!-- Спасибо за заявку-->
<div class="modal modal--center" id="thanks-modal">
    <div class="modal__overlay" data-modal-close=""></div>
    <div class="modal__inner modal__inner--center modal__inner--small">
        <div class="modal__head">
            <div class="modal__title">Спасибо за вашу заявку!</div>
            <button class="modal__close modal__close--center" aria-label="Закрыть модальное окно" data-modal-close=""></button>
        </div>
        <div class="modal__content">
            <div class="modal__text">Наши менеджеры свяжутся с вами в ближайшее время. <br/> Нет времени ждать? Перезвоните нам.</div>
            <div class="modal__contacts">
                <div class="modal__contacts-wrapper">
                    <div class="modal__contacts-links">
                        <a class="modal__contacts-item" href="tel:89883429798" title="Позвонить нам">+7 988 342-97-98</a>
                    </div>
                    <a class="button button--large button--yellow-two button--full" title="На главную" href="{{ route('home') }}"><span class="button__text">На главную</span></a>
                </div>
            </div>
        </div>
    </div>
</div>

front/resources/views/partials/feedback.blade.php
<section class="section section--default feedback">
    <div class="feedback__wrap">
        <h4 class="feedback__title reset-mt">Остались вопросы?</h4>
        <p class="feedback__text">Оставьте заявку и мы свяжемся с вами в ближайшее время для консультации</p>
        <form class="form form--feedback ajax-form" id="feedback-form" action="{{ route('callbackSend') }}" method="post">
            <div class="field">
                <input class="field__input field__input--default  field__input--white" id="feedback-name" type="text" name="name" required="required"/>
                <label class="field__label field__label--white" for="feedback-name">Ваше имя</label>
            </div>
            <div class="field">
                <input class="field__input field__input--default  field__input--white" id="feedback-phone" type="tel" name="phone" required="required"/>
                <label class="field__label field__label--white" for="feedback-phone">Телефон</label>
            </div>
            <button class="button button--large button--yellow button--full button--text-white" id="feedback-button" type="submit">
                <span class="button__text">Жду звонка</span>
            </button>
            <span class="feedback__thanks--text" id="thanks-text">Спасибо, с вами в скором времени свяжуться</span>
        </form>
        <div class="form-message form-message--white">Нажимая на кнопку вы даете согласие на обработку персональных данных и соглашаетесь с 
            <a href="#" title="Соглашение на обработку персональных данных">Политикой конфиденциальности</a>
        </div>
    </div>
</section>
<style>
    .feedback__thanks--text{
        width: 100%;
        display: none;
        align-items: center;
        justify-content: center;
        font-size: 22px;
        font-weight: bold;
    }
</style>

front/resources/views/partials/footer.blade.php
<div class="footer__wrapper">
    @include('partials.feedback')
    <footer class="footer">
        <div class="container">
            <div class="footer__main"><a class="footer__logo" href="{{ route('home') }}" title="Родные просторы">
                    <img class="footer__logo-img" src="{{ asset("/assets/img/logo.svg") }}" alt="Родные просторы" width="162" height="64" loading="lazy"/>
                </a>
                <div class="footer__nav">
                    <h5 class="footer__title">Отдыхающим</h5>
                    <ul class="footer__menu">
                        <li class="footer__menu-item"><a class="footer__menu-link" href="{{ route('gallery') }}" title="Галерея">Галерея</a></li>
                        <li class="footer__menu-item"><a class="footer__menu-link" href="{{ route('services.index') }}" title="Услуги">Услуги</a></li>
                        <li class="footer__menu-item"><a class="footer__menu-link" href="{{ route('rules') }}" title="Проживание">Проживание</a></li>
                        <li class="footer__menu-item"><a class="footer__menu-link" href="{{ route('contacts') }}" title="Контакты">Контакты</a></li>
                    </ul>
                </div>
                <div class="footer__address">
                    <h5 class="footer__title">Адрес</h5>
                    <div class="footer__address-text">Краснодарский край <br/>станица Гостагаевская г-к Анапа</div>
                    <a class="footer__address-link" target="_blank" href="https://yandex.ru/profile/92803645800?no-distribution=1&source=wizbiz_new_map_single" title="Проложить маршрут">Проложить маршрут</a>
                </div>
                <div class="footer__contacts">
                    <h5 class="footer__title">Связаться с нами</h5>
                    <div class="footer__contacts-main">
                        <div class="footer__contacts-blocks">
                            <div class="footer__contacts-block">
                                <svg class="footer__contacts-icon" role="img">
                                    <use xlink:href="{{ asset("/assets/img/icons.svg?v=1693225697529#envelope") }}"></use>
                                </svg>
                                <div class="footer__contacts-links"><a class="footer__contacts-item" href="mailto:r.prostori@mail.ru" title="Написать нам"> r.prostori@mail.ru</a></div>
                            </div>
                            <div class="footer__contacts-block">
                                <svg class="footer__contacts-icon" role="img">
                                    <use xlink:href="{{ asset("/assets/img/icons.svg?v=1693225697529#phone") }}"></use>
                                </svg>
                                <div class="footer__contacts-links">
                                    <a class="footer__contacts-item" href="tel:89883429798" title="Позвонить нам">+7 988 342-97-98</a>
                                </div>
                            </div>
                        </div>
                        <ul class="footer__social">
                            <li class="footer__social-item"><a class="footer__social-link" href="https://t.me/rodnieprostori" title="Мы в Телеграмме">
                                    <svg role="img">
                                        <use xlink:href="{{ asset("/assets/img/icons.svg?v=1693225697529#telegramm") }}"></use>
                                    </svg></a></li>
                            <li class="footer__social-item"><a class="footer__social-link" href="https://vk.com/r.prostori" title="Мы в Vk">
                                    <svg role="img">
                                        <use xlink:href="{{ asset("/assets/img/icons.svg?v=1693225697529#vk") }}"></use>
                                    </svg></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="footer__bottom">
                <div class="footer__bottom-item">© 2008 — 2023 Все права защищены</div>
                <div class="footer__bottom-item">
                    <a class="footer__bottom-link" href="#" title="Пользовательское соглашение">Пользовательское соглашение</a>
                </div>
                <div class="footer__bottom-item">
                    <a class="footer__bottom-link" href="#" title="Соглашение на обработку персональных данных">Политика конфиденциальности</a>
                </div>
            </div>
        </div>
    </footer>
</div>

front/resources/views/partials/top.blade.php
<div class="top">
    <picture class="top__picture">
        <source srcset="{{ asset("assets/img/$image.jpg") }}" media="(min-width: 768px)">
        <img class="top__img" src="{{ asset("assets/img/$image--xs.jpg") }}" alt="Домики" width="720" height="902">
    </picture>
    <div class="container top__container">
        <h1 class="reset top__title">{{ $title }}</h1>
        @if($top_text)
            <span class="top__text">
                {{ $top_text }}
            </span>
        @endif
    </div>
</div>